homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret timezone
  customize: !include includes/customize.yaml
  whitelist_external_dirs:
    - !secret home_assistant_directory

frontend:
  themes: !include_dir_merge_named includes/themes/

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  trusted_networks:
    - !secret lan
    - !secret vpn
    - !secret work
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  icon: mdi:home-map-marker
  radius: 100
zone 2:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  icon: mdi:map-marker
  radius: 100



apple_tv:
  - host: !secret atv1_ip
    login_id: !secret atv1_loginid
    name: Living Room TV

config:

device_tracker:
  - platform: nmap_tracker
    hosts: !secret nmap_range
    scan_options: " -sP "

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

ecobee:
  api_key: !secret ecobee_api_key

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - script
    - switch
  entity_config:
    script.update_location_guilty_spark:
      expose: false
    script.update_location_cortana:
      expose: false
    script.bar_lamp_arrival:
      expose: false
    script.office_record_on:
      expose: false
    script.office_record_off:
      expose: false

history: !include includes/history.yaml

ios:

logbook:

media_player:
  - platform: cast
  - platform: cast
    host: !secret office_speaker_ip
  - platform: cast
    host: !secret kitchen_speaker_ip
  - platform: cast
    host: !secret bedroom_cast_ip

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

recorder:
  purge_keep_days: 30

sun:

tts:
  - platform: google

updater:

zoneminder:
  host: !secret zm_host
  username: !secret zm_user
  password: !secret zm_pass

automation: !include_dir_merge_list includes/automation
binary_sensor: !include includes/binary_sensor.yaml
camera: !include includes/camera.yaml
group: !include includes/group.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
notify: !include includes/notify.yaml
scene: !include includes/scene.yaml
script: !include includes/script.yaml
sensor: !include includes/sensor.yaml
shell_command: !include includes/shell_command.yaml
switch: !include includes/switch.yaml
