base_url: url.com:1234
http_password: api_password
home_assistant_directory: .travis/
ssl_cert: .travis/blankfile
ssl_key: .travis/blankfile
lan: 1.1.1.0/24
vpn: 2.2.2.0/24
work: 3.3.3.3

home_latitude: 12.345
home_longitude: 12.345
home_elevation: 123

work_latitude: 12.345
work_longitude: 12.345

timezone: America/New_York



arbiter_host: host
arbiter_port: 1234

atv1_ip: 1.1.1.1
atv1_loginid: login

bedroom_cast_ip: 1.1.1.1

dns_arbiter: host
dns_genesis: host
dns_infinity: host
dns_portal: host
dns_witness: host
dns_resolver: 1.1.1.1

duckdns_domain: domain1,domain2,domain3
duckdns_token: token

ecobee_api_key: key

foscam_ip: 1.1.1.1
foscam_user: user
foscam_pass: pass

genesis_host: host
genesis_port: 1234

google_api_key: key
home_address: home
work_address: work

google_assistant_access_token: token
google_assistant_api_key: key
google_assistant_client_id: client
google_assistant_project_id: project

homeassistant_db_file: .travis/blankfile

infinity_host: host
infinity_port: 1234

kitchen_speaker_ip: 1.1.1.1

mqtt_broker: 1.1.1.1
mqtt_port: 1234
mqtt_client_id: client

nest_client_id: client
nest_client_secret: secret

office_speaker_ip: 1.1.1.1

pihole_command_on: "on"
pihole_command_off: "off"
pihole_command_state: "state"
pihole_ip: 1.1.1.1

qnap_ip: 1.1.1.1
qnap_port: 1234
qnap_user: user
qnap_pass: pass

slack_api_key: key
slack_default_channel: '#channel'

witness_host: host
witness_port: 1234

wunderground_api_key: key
pws_id: pws

zoneminder_host: 1.1.1.1
zoneminder_user: user
zoneminder_pass: pass
