- platform: template
  sensors:
    guilty_spark:
      value_template: '{% if is_state("device_tracker.guilty_spark", "not_home") %}Away{% elif is_state("device_tracker.guilty_spark", "home") %}Home{% else %}{{ states("device_tracker.guilty_spark") }}{% endif %}'
    cortana:
      value_template: '{% if is_state("device_tracker.cortana", "not_home") %}Away{% elif is_state("device_tracker.cortana", "home") %}Home{% else %}{{ states("device_tracker.cortana") }}{% endif %}'

- platform: pi_hole
  host: !secret pihole_ip

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /var/cache/zoneminder/
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: since_last_boot

- platform: cert_expiry
  host: !secret arbiter_host
  port: !secret arbiter_port
  name: ssl_arbiter

- platform: cert_expiry
  host: !secret genesis_host
  port: !secret genesis_port
  name: ssl_genesis

- platform: cert_expiry
  host: !secret infinity_host
  port: !secret infinity_port
  name: ssl_infinity

- platform: cert_expiry
  host: !secret witness_host
  port: !secret witness_port
  name: ssl_witness

- platform: filesize
  file_paths:
    - !secret homeassistant_db_file

- platform: qnap
  host: !secret qnap_ip
  port: !secret qnap_port
  ssl: true
  verify_ssl: false
  username: !secret qnap_user
  password: !secret qnap_pass
  monitored_conditions:
    - status
    - system_temp
    - cpu_temp
    - cpu_usage
    - memory_free
    - memory_used
    - memory_percent_used
    - network_link_status
    - network_tx
    - network_rx
    - drive_smart_status
    - drive_temp
    - volume_size_free
    - volume_size_used
    - volume_percentage_used

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: dnsip

- platform: dnsip
  hostname: !secret dns_arbiter
  resolver: !secret dns_resolver

- platform: dnsip
  hostname: !secret dns_genesis
  resolver: !secret dns_resolver

- platform: dnsip
  hostname: !secret dns_infinity
  resolver: !secret dns_resolver

- platform: dnsip
  hostname: !secret dns_portal
  resolver: !secret dns_resolver

- platform: dnsip
  hostname: !secret dns_witness
  resolver: !secret dns_resolver

- platform: google_travel_time
  name: Home to Work
  api_key: !secret google_api_key
  origin: !secret home_address
  destination: !secret work_address

- platform: google_travel_time
  name: Work to Home
  api_key: !secret google_api_key
  origin: !secret work_address
  destination: !secret home_address

- platform: google_travel_time
  name: Nick to Home
  api_key: !secret google_api_key
  origin: device_tracker.guilty_spark
  destination: !secret home_address

- platform: google_travel_time
  name: Melinda to Home
  api_key: !secret google_api_key
  origin: device_tracker.cortana
  destination: !secret home_address

- platform: google_travel_time
  name: Nick to Melinda
  api_key: !secret google_api_key
  origin: device_tracker.guilty_spark
  destination: device_tracker.cortana

- platform: wunderground
  api_key: !secret wunderground_api_key
  pws_id: !secret pws_id
  monitored_conditions:
    - alerts
    - dewpoint_f
    - feelslike_f
    - location
    - observation_time
    - precip_1hr_in
    - precip_today_in
    - relative_humidity
    - station_id
    - temp_f
    - visibility_mi
    - weather
    - wind_dir
    - wind_gust_mph
    - wind_mph

- platform: zoneminder

- platform: command_line
  name: ZoneMinder State
  command: "/home/homeassistant/.homeassistant/bin/zm_state.py --get"
  scan_interval: 5

- platform: template
  sensors:
    alarm_state:
      value_template: '{% if is_state("input_boolean.alarm", "on") %}ALERT{% else %}Clear{% endif %}'
